import Head from "next/head";

import RootLayout from "@/components/Layout/RootLayout";
import ProductCard from "@/components/ProductCard";

export default function Home({products}) {
  console.log(products);
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div>
          <ProductCard/>
        </div>
      </main>
    </>
  );
}

Home.getLayout = function getLayout(page) {
  return <RootLayout>{page}</RootLayout>;
};

export const getStaticProps = async () => {
  const res = await fetch('http://localhost:3000/api/products')
  const data = await res.json()

  return {
    props : {
      products : data.data
    }
  }
}